import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyAction,advance} from '../lib/club.ts';
function setup(){const s=initialState();s.members=Array.from({length:20},(_,i)=>({id:String(i),name:'Student '+i,email:i+'@example.edu',admin:i===19,blocked:false}));return s;}
test('starts only at four, lasts 30 minutes, and rejects duplicate participation',()=>{const s=setup();for(let i=0;i<3;i++)applyAction(s,'join',{},s.members[i],1000);assert.equal(s.courts[0].players.length,0);applyAction(s,'join',{},s.members[3],2000);assert.deepEqual(s.courts[0].players,['0','1','2','3']);assert.equal(s.courts[0].endsAt,1802000);assert.throws(()=>applyAction(s,'join',{},s.members[0],2001));});
test('fills three courts in FIFO order; expiry dispatches next four',()=>{const s=setup();for(let i=0;i<17;i++)applyAction(s,'join',{},s.members[i],1000);assert.equal(s.courts.flatMap(c=>c.players).length,12);assert.deepEqual(s.queue.map(q=>q.id),['12','13','14','15','16']);advance(s,1801000);assert.deepEqual(s.courts[0].players,['12','13','14','15']);assert.equal(s.courts[0].endsAt,3601000);assert.deepEqual(s.queue.map(q=>q.id),['16']);assert.equal(s.courts[1].players.length,0);});
test('closing returns players safely; no closed court starts',()=>{const s=setup();for(let i=0;i<4;i++)applyAction(s,'join',{},s.members[i],1000);applyAction(s,'close',{court:1},s.members[19],2000);assert.equal(s.courts[0].players.length,0);assert.equal(s.courts[0].closed,true);assert.deepEqual(s.courts[1].players,['0','1','2','3']);assert.equal(new Set([...s.queue.map(p=>p.id),...s.courts.flatMap(c=>c.players)]).size,4);});
test('removal stops a partial match, replaces from queue, starts a fresh full session',()=>{const s=setup();s.courts[1].closed=true;s.courts[2].closed=true;for(let i=0;i<5;i++)applyAction(s,'join',{},s.members[i],1000);applyAction(s,'remove',{member:'2'},s.members[19],5000);assert.deepEqual(s.courts[0].players,['0','1','3','4']);assert.equal(s.courts[0].endsAt,1805000);});
test('authorization, blocked member and cancellation boundaries',()=>{const s=setup();assert.throws(()=>applyAction(s,'close',{court:1},s.members[0],1000));applyAction(s,'block',{member:'0'},s.members[19],1000);assert.throws(()=>applyAction(s,'join',{},s.members[0],1000));applyAction(s,'join',{},s.members[1],1000);applyAction(s,'leave',{},s.members[1],2000);assert.equal(s.queue.length,0);assert.throws(()=>applyAction(s,'role',{member:'19'},s.members[19],3000));});
const snapshot=c=>({court:c.id,expectedStartedAt:c.startedAt,expectedPlayers:[...c.players],expectedNextPlayers:[...(c.nextPlayers||[])]});
test('admin selects a court and four idle or queued students; exactly four required',()=>{const s=setup(),admin=s.members[19];const body=snapshot(s.courts[2]);assert.throws(()=>applyAction(s,'assign',{...body,members:['0','1','2']},admin,1000));assert.throws(()=>applyAction(s,'assign',{...body,members:['0','1','2','2']},admin,1000));applyAction(s,'assign',{...body,members:['0','1','2','3']},admin,1000);assert.deepEqual(s.courts[2].players,['0','1','2','3']);assert.equal(s.courts[2].endsAt,1801000);});
test('changing a live roster preserves the clock and returns replaced players to queue',()=>{const s=setup(),admin=s.members[19];for(let i=0;i<4;i++)applyAction(s,'join',{},s.members[i],1000);applyAction(s,'assign',{...snapshot(s.courts[0]),members:['0','1','2','4']},admin,2000);assert.equal(s.courts[0].endsAt,1801000);assert.deepEqual(s.courts[0].players,['0','1','2','4']);assert.deepEqual(s.queue.map(p=>p.id),['3']);});
test('next group is reserved for its court and gets priority at expiry',()=>{const s=setup(),admin=s.members[19];s.courts[1].closed=s.courts[2].closed=true;for(let i=0;i<8;i++)applyAction(s,'join',{},s.members[i],1000);applyAction(s,'plan',{...snapshot(s.courts[0]),members:['4','5','6','7']},admin,2000);assert.equal(s.queue.length,0);assert.throws(()=>applyAction(s,'join',{},s.members[4],3000));for(let i=8;i<12;i++)applyAction(s,'join',{},s.members[i],3000);advance(s,1801000);assert.deepEqual(s.courts[0].players,['4','5','6','7']);assert.deepEqual(s.queue.map(p=>p.id),['8','9','10','11']);assert.equal(s.courts[0].endsAt,3601000);});
test('rejects occupied, reserved, blocked and stale selections',()=>{const s=setup(),admin=s.members[19];for(let i=0;i<8;i++)applyAction(s,'join',{},s.members[i],1000);assert.throws(()=>applyAction(s,'assign',{...snapshot(s.courts[0]),members:['0','1','2','4']},admin,2000));applyAction(s,'plan',{...snapshot(s.courts[0]),members:['8','9','10','11']},admin,2000);assert.throws(()=>applyAction(s,'assign',{...snapshot(s.courts[2]),members:['8','12','13','14']},admin,2000));const old=snapshot(s.courts[0]);applyAction(s,'assign',{...old,members:['0','1','2','12']},admin,2000);assert.throws(()=>applyAction(s,'assign',{...old,members:['0','1','2','13']},admin,2000));s.members[14].blocked=true;assert.throws(()=>applyAction(s,'assign',{...snapshot(s.courts[0]),members:['0','1','2','14']},admin,2000));});
test('cancelling or blocking a reserved player releases the planned group without duplicates',()=>{const s=setup(),admin=s.members[19];s.courts[1].closed=s.courts[2].closed=true;for(let i=0;i<4;i++)applyAction(s,'join',{},s.members[i],1000);applyAction(s,'plan',{...snapshot(s.courts[0]),members:['4','5','6','7']},admin,2000);applyAction(s,'block',{member:'4'},admin,3000);assert.deepEqual(s.courts[0].nextPlayers,[]);assert.deepEqual(s.queue.map(p=>p.id),['5','6','7']);applyAction(s,'plan',{...snapshot(s.courts[0]),members:['5','6','7','8']},admin,3000);applyAction(s,'cancel-plan',snapshot(s.courts[0]),admin,4000);assert.deepEqual(s.queue.map(p=>p.id),['5','6','7','8']);assert.equal(new Set([...s.queue.map(p=>p.id),...s.courts.flatMap(c=>[...c.players,...(c.nextPlayers||[])])]).size,8);});
