'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {Activity,ArrowRight,ArrowUp,Check,Clock3,LogOut,Mail,ShieldCheck,Users,LayoutGrid,LockKeyhole,Plus,RefreshCw,UserRound,X,Play,Settings2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {State,Member,Court,initialState,advance,applyAction} from '@/lib/club';
type View=State & {me:(Member & {expiresAt:number})|null;serverNow:number;authReady:boolean;domain:string};
const time=(seconds:number)=>{const s=Math.max(0,Math.ceil(seconds));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};
function demoState():View {
 const s=initialState(),now=Date.now();
 const names=['Alex Chen','Emily Wang','Jason Lee','Sarah Liu','Ryan Zhang','Chloe Lin','Daniel Wu','Mia Huang','Kevin Yang','Ashley Li','Eric Zhou','Olivia Sun','Ethan Liu','Sophie Chen','Nathan Park','Grace Kim','Lucas Nguyen','Ava Tran','Jack Wilson','体验学生'];
 s.members=names.map((name,i)=>({id:'demo-'+i,name,email:'student'+(i+1)+'@example.edu',blocked:false,admin:i===19}));
 const elapsed=[1065000,420000,180000];
 s.courts=s.courts.map((c,i)=>({...c,players:s.members.slice(i*4,i*4+4).map(m=>m.id),startedAt:now-elapsed[i],endsAt:now-elapsed[i]+1800000}));
 s.queue=s.members.slice(12,20).map((m,i)=>({id:m.id,joinedAt:now-(8-i)*45000}));
 return {...s,me:{...s.members[19],expiresAt:now+14400000},serverNow:now,authReady:false,domain:'unlv.nevada.edu'};
}
export default function Home(){
 const [data,setData]=useState<View|null>(null),[demo,setDemo]=useState(false),[tab,setTab]=useState('courts'),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[login,setLogin]=useState(false),[step,setStep]=useState(0),[email,setEmail]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[authError,setAuthError]=useState(''),[cooldown,setCooldown]=useState(0);
 const [arranging,setArranging]=useState<{court:Court;next:boolean}|null>(null),[selected,setSelected]=useState<string[]>([]);
 const [confirm,setConfirm]=useState<{title:string;description:string;action:string;body:any}|null>(null),[editing,setEditing]=useState<Member|null>(null),[editName,setEditName]=useState('');
 const mode=useRef(false),requestId=useRef(0);
 const refresh=useCallback(async()=>{const id=++requestId.current;try{const r=await fetch('/api/club',{cache:'no-store'});const d=await r.json() as View & {error?:string};if(!r.ok)throw Error(d.error);if(mode.current||id!==requestId.current)return;setData(d);setOffset(d.serverNow-Date.now());setError('');}catch(e){if(!mode.current)setError(e instanceof Error?e.message:'连接暂时中断。');}},[]);
 useEffect(()=>{if(!demo){refresh();const t=setInterval(refresh,3000);return()=>clearInterval(t);}},[demo,refresh]);
 useEffect(()=>{const t=setInterval(()=>{setNow(Date.now()+offset);if(mode.current)setData(d=>d?({...d,...advance(structuredClone(d)),serverNow:Date.now()}):d);},1000);return()=>clearInterval(t);},[offset]);
 const domain=data?.domain||'unlv.nevada.edu',me=data?.me,validMe=me&&me.expiresAt>now?me:null,admin=!!validMe?.admin;
 const member=(id:string)=>data?.members.find(m=>m.id===id);
 const myQueue=data?.queue.findIndex(p=>p.id===me?.id)??-1,myCourt=data?.courts.find(c=>c.players.includes(me?.id||'')),myPlanned=data?.courts.find(c=>c.nextPlayers?.includes(me?.id||''));
 function toggleDemo(){mode.current=!demo;requestId.current++;setDemo(!demo);setTab('courts');setError('');setOffset(0);setData(!demo?demoState():null);setConfirm(null);setArranging(null);}
 async function act(action:string,body:any={}){if(busy)return;setBusy(true);try{if(demo){if(!data?.me)return;const s=structuredClone(data);applyAction(s,action,body,s.me!);s.me={...s.members.find(m=>m.id===s.me!.id)!,expiresAt:s.me!.expiresAt};setData(s);}else{const r=await fetch('/api/club',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const d=await r.json() as View & {error?:string};if(!r.ok)throw Error(d.error);setData(d);}toast.success(action==='join'?'已加入排队':action==='leave'?'已取消排队':'已更新');return true;}catch(e){toast.error(e instanceof Error?e.message:'操作失败');return false;}finally{setBusy(false);}}
 async function auth(action:string){setBusy(true);setAuthError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email,name,code})});const d=await r.json() as View & {error?:string};if(!r.ok)throw Error(d.error);if(action==='send'){setStep(1);setCooldown(Date.now()+60000);toast.success('验证码已发送，请查看学校邮箱。');}else{setLogin(false);setStep(0);setCode('');await refresh();toast.success(action==='logout'?'已退出登录':'邮箱验证成功');}}catch(e){setAuthError(e instanceof Error?e.message:'请稍后重试。');if(action==='logout')toast.error('退出失败，请重试。');}finally{setBusy(false);}}
 const ask=(title:string,description:string,action:string,body:any)=>setConfirm({title,description,action,body});
 function arrange(c:Court,next:boolean){setArranging({court:structuredClone(c),next});setSelected(next?[...(c.nextPlayers||[])]:[...c.players]);}
 function courtCard(c:Court,manage=false){const active=c.players.length===4,remaining=c.endsAt?(c.endsAt-now)/1000:0;return <article className={'court-card '+(c.closed?'is-closed':'')} key={c.id}><div className="court-heading"><div><span className="eyebrow">COURT 0{c.id}</span><h3>{c.id} 号场地</h3></div><span className={'badge '+(c.closed?'gray':active?'green':'light')}>{c.closed?'暂停使用':active?'进行中':'等待开场'}</span></div><div className={'court-map '+(active?'occupied':'')} aria-label={'场地示意图：'+(active?'4 人正在打球':'空场')}><svg viewBox="0 0 300 150" preserveAspectRatio="none" aria-hidden="true"><rect x="14" y="12" width="272" height="126"/><path d="M14 26H286 M14 124H286 M44 12V138 M256 12V138 M108 12V138 M192 12V138 M14 75H108 M192 75H286"/><path className="net" d="M150 7V143"/></svg>{active?<div className="player-map">{c.players.map((id,i)=><div className={'court-person p'+i} key={id}><span>{member(id)?.name.slice(0,1)||'?'}</span><b>{member(id)?.name||'学生'}</b></div>)}</div>:<div className="court-empty">{c.closed?<LockKeyhole size={23}/>:<Users size={26}/>}<span>{c.closed?'场地已关闭':'四人就位，即可开场'}</span></div>}</div><div className="court-timer"><div><Clock3 size={16}/><span>{active?'本场剩余':'每场时长'}</span></div><strong>{active?time(remaining):'30:00'}</strong></div><div className="timer-track"><i style={{width:active?Math.max(0,remaining/1800*100)+'%':'0%'}}/></div><div className="court-foot"><span><Users size={15}/>{c.players.length} / 4 人</span><span>{active?'到时自动换场':c.closed?'由管理员重新开放':'按排队顺序分配'}</span></div>{(c.nextPlayers?.length||0)>0&&<div className="next-roster"><b>下一场 · 管理员指定</b><span>{c.nextPlayers!.map(id=>member(id)?.name).join("、")}</span><small>本场结束后，四人自动开场 30 分钟</small></div>}{manage&&<><div className="arrange-actions"><button className="btn primary small" disabled={busy||c.closed} onClick={()=>arrange(c,false)}>{active?"调整本场人员":"安排四人开场"}</button><button className="btn outline small" disabled={busy||c.closed||!active} onClick={()=>arrange(c,true)}>{c.nextPlayers?.length?"修改下一场":"安排下一场"}</button></div><div className="court-actions"><button disabled={busy||!active} className="btn small outline" onClick={()=>ask('结束这场比赛？','本场四人将离场。优先开始管理员安排的下一场，否则按队列分配。','end',{court:c.id})}>结束本场</button><button disabled={busy} className="btn small outline" onClick={()=>c.closed?act('open',{court:c.id}):ask('关闭 '+c.id+' 号场地？','当前及下一场人员会回到队首，取消指定场次并停止计时。','close',{court:c.id})}>{c.closed?'重新开放':'关闭场地'}</button></div></>}</article>}
 return <><Toaster richColors position="top-center"/><div className="brand-stripe"/><header className="site-header"><a href="/" className="brand" aria-label="UNLV Badminton 首页"><span className="wordmark">UNLV<span>BADMINTON</span></span><span className="brand-divider"/><span className="brand-name">羽毛球学生组织<small>COURT RESERVATIONS</small></span></a><div className="header-actions"><button className="text-button" onClick={toggleDemo}>{demo?'退出演示':'体验演示'}</button>{validMe?<><span className="signed-name"><UserRound size={16}/>{validMe.name}</span>{!demo&&<button className="icon-button" aria-label="退出登录" disabled={busy} onClick={()=>auth('logout')}><LogOut size={18}/></button>}</>:<button className="btn primary small" onClick={()=>{setAuthError('');setLogin(true);}}><UserRound size={16}/>学生登录</button>}</div></header>
 <Tabs value={tab} onValueChange={setTab}><div className="nav-wrap"><TabsList variant="line" className="main-tabs"><TabsTrigger value="courts"><LayoutGrid/>场地与排队</TabsTrigger><TabsTrigger value="admin"><ShieldCheck/>管理员</TabsTrigger></TabsList><span className="nav-note">4 人开场 <span>·</span> 每场 30 分钟</span></div><main className="workspace">{demo&&<div className="demo-banner"><Play size={16}/><span><b>互动演示</b> · 使用虚构人员，可体验排队和管理员操作；退出后重置，不产生真实预约。</span><button onClick={toggleDemo}>退出演示 <X size={14}/></button></div>}{error&&<div className="error-banner" role="alert">{error}<button onClick={refresh}><RefreshCw size={15}/>重新连接</button></div>}
 <TabsContent value="courts"><div className="page-heading"><div><p className="eyebrow red">LET’S PLAY</p><h1>场地与排队<span className={'live '+(error?'offline':'')}>{error?'连接中断':data?(demo?'演示数据':'每 3 秒同步'):'正在连接'}</span></h1><p>加入队列，凑齐四人，开启下一场。</p></div><div className="date-stamp"><span>LAS VEGAS</span><strong suppressHydrationWarning>{new Date(now).toLocaleDateString('zh-CN',{timeZone:'America/Los_Angeles',month:'long',day:'numeric',weekday:'long'})}</strong></div></div>
 <div className="stats-strip"><div><span>正在打球</span><strong>{data?data.courts.reduce((n,c)=>n+c.players.length,0):'—'}<small>人</small></strong><Users/></div><div><span>排队等待</span><strong>{data?data.queue.length:'—'}<small>人</small></strong><Clock3/></div><div><span>空闲场地</span><strong>{data?data.courts.filter(c=>!c.closed&&!c.players.length).length:'—'}<small>/ 3</small></strong><LayoutGrid/></div></div>
 <a className="mobile-queue-link" href="#waiting-queue"><Users size={18}/><span>{myQueue>=0?`你排在第 ${myQueue+1} 位`:myCourt?`你在 ${myCourt.id} 号场地`:myPlanned?`${myPlanned.id} 号场地下一场`:`查看等待队列 · ${data?.queue.length??0} 人`}</span><ArrowRight size={17}/></a><div className="section-heading"><h2>实时场地 <span>LIVE COURTS</span></h2><span className="section-note desktop-note">每场 4 人 · 双打</span><span className="mobile-court-hint">左右滑动查看 3 个场地</span></div><div className="courts-grid">{data?data.courts.map(c=>courtCard(c)):[1,2,3].map(id=><div className="court-card loading-card" key={id}><h3>{id} 号场地</h3><p>{error?'等待重新连接':'正在获取场地状态…'}</p></div>)}</div>
 <div className="lower-grid"><section id="waiting-queue" className="queue-panel"><div className="panel-heading"><div><h2>等待队列 <span className="count">{data?.queue.length??'—'}</span></h2><p>未指定场次时，按队列顺序分配；指定场次显示在对应场地下方。</p></div><span className="eyebrow">UP NEXT</span></div>{data?.queue.length?<Table><TableHeader><TableRow><TableHead className="rank-col">顺序</TableHead><TableHead>学生</TableHead><TableHead>已等待</TableHead><TableHead className="status-col">状态</TableHead></TableRow></TableHeader><TableBody>{data.queue.map((p,i)=><TableRow className={p.id===me?.id?'my-row':''} key={p.id}><TableCell><span className={'rank '+(i<4?'next':'')}>{String(i+1).padStart(2,'0')}</span></TableCell><TableCell><div className="person"><span className={'avatar tone'+i%4}>{member(p.id)?.name.slice(0,1)}</span><b>{member(p.id)?.name}{p.id===me?.id&&<small>你</small>}</b></div></TableCell><TableCell>{Math.max(0,Math.floor((now-p.joinedAt)/60000))} 分钟</TableCell><TableCell><span className={'queue-status '+(i<4?'next':'')}>{i<4?'下一组':'等待中'}</span></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-queue"><Users size={30}/><h3>{data?'还没有人排队':'正在读取队列'}</h3><p>{data?'加入队列，成为下一场的第一位。':'场地与队列将同步显示在这里。'}</p></div>}<div className="queue-bottom"><span className="mini-line"/>不足四人时继续等待，不开始计时。</div></section>
 <aside><section className="join-panel"><div className="join-top"><span className="eyebrow">YOUR NEXT GAME</span><Users size={24}/></div><h2>{myCourt?'正在场上，尽情挥拍':myPlanned?'下一场已为你安排':myQueue>=0?'你已在队列中':'准备好上场了吗？'}</h2><p>{myCourt?`你在 ${myCourt.id} 号场地，本场剩余 ${time(((myCourt.endsAt||now)-now)/1000)}。`:myPlanned?`管理员已安排你在 ${myPlanned.id} 号场地下一场上场，请在场边等候。`:myQueue>=0?`当前排在第 ${myQueue+1} 位，请留意场地状态。`:'使用学校邮箱登录，即可加入排队。'}</p>{validMe?<><div className="session-info"><ShieldCheck size={15}/>{demo?'演示账号':`登录剩余 ${time((validMe.expiresAt-now)/1000)}`}</div><button className="btn join-btn" disabled={busy||!!myCourt||!!myPlanned||!!validMe.blocked||!!error} onClick={()=>act(myQueue>=0?'leave':'join')}>{validMe.blocked?'预约权限已暂停':myCourt?'本场进行中':myPlanned?'已安排下一场':myQueue>=0?'取消排队':'加入排队'}{!myCourt&&<ArrowRight size={18}/>}</button></>:<button className="btn join-btn" onClick={()=>{setAuthError('');setLogin(true);}}>学校邮箱登录<ArrowRight size={18}/></button>}<small><LockKeyhole size={13}/>一次验证 · 登录有效期 4 小时</small></section><section className="rules-panel"><h3>上场须知</h3><ol><li><span>01</span>每人同时只能占一个排队或场地名额。</li><li><span>02</span>四人满员后，开始 30 分钟计时。</li><li><span>03</span>到时请让出场地，可重新加入队尾。</li></ol></section></aside></div></TabsContent>
 <TabsContent value="admin"><div className="page-heading"><div><p className="eyebrow red">CLUB OPERATIONS</p><h1>管理员控制台</h1><p>管理场地、调整队列与学生权限。</p></div><span className="admin-tag"><ShieldCheck size={16}/>{admin?'管理员权限':'仅限授权管理员'}</span></div>{!admin?<section className="admin-locked"><div className="lock-circle"><ShieldCheck size={35}/></div><h2>需要管理员账号</h2><p>使用被授权的学校邮箱登录后，才能管理场地和学生。</p><button className="btn primary" onClick={()=>{setAuthError('');setLogin(true);}}>管理员邮箱登录 <ArrowRight size={17}/></button><button className="text-button" onClick={toggleDemo}>体验管理员演示</button></section>:<><div className="section-heading"><h2>场地控制</h2><span className="section-note desktop-note">所有变更将同步给学生</span><span className="mobile-court-hint">左右滑动切换场地</span></div><div className="courts-grid">{data?.courts.map(c=>courtCard(c,true))}</div><section className="queue-panel admin-members"><div className="panel-heading"><div><h2>学生管理 <span className="count">{data?.members.length}</span></h2><p>移除场上人员时，其余三人回到队首，重新凑齐四人开场。</p></div><Settings2 size={21}/></div><Table><TableHeader><TableRow><TableHead>学生</TableHead><TableHead>学校邮箱</TableHead><TableHead>当前状态</TableHead><TableHead>管理操作</TableHead></TableRow></TableHeader><TableBody>{data?.members.map(m=>{const c=data.courts.find(c=>c.players.includes(m.id)),planned=data.courts.find(c=>c.nextPlayers?.includes(m.id)),q=data.queue.findIndex(p=>p.id===m.id);return <TableRow key={m.id}><TableCell><div className="person"><span className="avatar">{m.name[0]}</span><b>{m.name}{m.admin&&<small>管理员</small>}</b></div></TableCell><TableCell>{m.email}</TableCell><TableCell><span className={'badge '+(m.blocked?'gray':c?'green':'light')}>{m.blocked?'已暂停':c?c.id+' 号场地':planned?planned.id+' 号场地下一场':q>=0?'排队第 '+(q+1)+' 位':'未预约'}</span></TableCell><TableCell><div className="member-actions"><button disabled={busy} onClick={()=>{setEditing(m);setEditName(m.name);}}>改名</button>{q>0&&<button disabled={busy} onClick={()=>ask('将 '+m.name+' 移到队首？','此操作将改变学生上场顺序。','priority',{member:m.id})}><ArrowUp size={14}/>置顶</button>}{(c||planned||q>=0)&&<button disabled={busy} onClick={()=>ask('移除 '+m.name+' 的预约？','该学生将退出队列、当前场地或指定场次；同组其余人员会回到队首。','remove',{member:m.id})}>移除</button>}{m.id!==me?.id&&<><button disabled={busy} onClick={()=>ask(m.admin?'撤销管理员权限？':'授予管理员权限？',m.name+' 的管理权限将立即更新。','role',{member:m.id})}>{m.admin?'撤销管理':'设为管理'}</button>{!m.admin&&<button disabled={busy} onClick={()=>ask(m.blocked?'恢复预约权限？':'暂停预约权限？',m.blocked?'该学生可以重新预约。':'该学生会被移出队列和场地，暂时不能预约。','block',{member:m.id})}>{m.blocked?'恢复':'暂停'}</button>}</>}</div></TableCell></TableRow>})}</TableBody></Table>{!data?.members.length&&<div className="empty-queue">学生验证邮箱后会出现在这里。</div>}</section></>}</TabsContent>
 <footer><span><b>UNLV</b> BADMINTON CLUB</span><span>学生组织场地排队系统 · 非学校官方预约系统</span></footer></main></Tabs>
 <Dialog open={login} onOpenChange={setLogin}><DialogContent className="login-dialog"><DialogHeader><div className="login-icon"><Mail size={25}/></div><DialogTitle>{step?'输入邮箱验证码':'用学校邮箱登录'}</DialogTitle><DialogDescription>{step?`验证码已发送至 ${email}。`:'无需密码。验证学校邮箱后，即可预约场地。'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();auth(step?'verify':'send');}}><label className="field">显示姓名<input required maxLength={40} placeholder="场上伙伴怎么称呼你？" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">学校邮箱<input required type="email" autoComplete="email" placeholder={'name@'+domain} value={email} disabled={step===1} onChange={e=>setEmail(e.target.value)}/></label>{step===1&&<div className="field"><label htmlFor="otp">六位验证码</label><InputOTP id="otp" maxLength={6} value={code} onChange={setCode} pattern="[0-9]*" autoComplete="one-time-code"><InputOTPGroup>{[0,1,2,3,4,5].map(i=><InputOTPSlot index={i} key={i} className="h-12 w-11 text-lg"/>)}</InputOTPGroup></InputOTP></div>}{!data?.authReady&&<div className="setup-notice">邮箱认证服务待配置。目前可通过「体验演示」查看完整流程。</div>}{authError&&<p className="form-error" role="alert">{authError}</p>}<button type="submit" className="btn primary full" disabled={busy||(step===1&&code.length!==6)}>{busy?'请稍候…':step?'验证并登录':'发送一次性验证码'}<ArrowRight size={17}/></button>{step===1&&<div className="resend"><button type="button" className="text-button" disabled={busy||now<cooldown} onClick={()=>auth('send')}>{now<cooldown?`${Math.ceil((cooldown-now)/1000)} 秒后可重发`:'重新发送'}</button><button type="button" className="text-button" onClick={()=>{setStep(0);setCode('');}}>更换邮箱</button></div>}<p className="login-foot"><ShieldCheck size={14}/>验证码仅可使用一次 · 登录有效期 4 小时</p></form></DialogContent></Dialog>
 <Dialog open={!!arranging} onOpenChange={v=>{if(!v&&!busy)setArranging(null);}}><DialogContent className="roster-dialog"><DialogHeader><DialogTitle>{arranging?.court.id} 号场地 · {arranging?.next?'安排下一场':arranging?.court.players.length?'调整本场人员':'安排四人开场'}</DialogTitle><DialogDescription>{arranging?.next?'选择四名学生，本场结束后优先在这个场地开始下一场。':arranging?.court.players.length?'选择本场四名学生。更换人员保留本场剩余时间，被替换的学生回到队首。':'选择四名学生，确认后立即开始 30 分钟计时。'} 已在其他场上或指定场次中的学生，需要先由管理员释放名额。</DialogDescription></DialogHeader><div className="selection-summary"><strong>已选 {selected.length} / 4 人</strong><span>每人同时仅能占一个名额</span></div><div className="roster-list">{data?.members.map(m=>{const playing=data.courts.find(c=>c.players.includes(m.id));const planned=data.courts.find(c=>c.nextPlayers?.includes(m.id));const unavailable=m.blocked||(!!playing&&!(playing.id===arranging?.court.id&&!arranging?.next))||(!!planned&&!(planned.id===arranging?.court.id&&arranging?.next));return <label className={'roster-option '+(unavailable?'unavailable':'')} key={m.id}><Checkbox checked={selected.includes(m.id)} disabled={busy||unavailable||(!selected.includes(m.id)&&selected.length===4)} onCheckedChange={checked=>setSelected(ids=>checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/><span className="avatar">{m.name[0]}</span><b>{m.name}</b><small>{m.blocked?'预约已暂停':playing?playing.id+' 号场地进行中':planned?planned.id+' 号场地下一场':data.queue.some(p=>p.id===m.id)?'排队中':'未预约'}</small></label>})}</div><div className="roster-submit">{arranging?.next&&!!arranging.court.nextPlayers?.length&&<button className="btn outline" disabled={busy} onClick={async()=>{if(arranging&&await act('cancel-plan',{court:arranging.court.id,expectedStartedAt:arranging.court.startedAt,expectedPlayers:arranging.court.players,expectedNextPlayers:arranging.court.nextPlayers||[]}))setArranging(null);}}>取消下一场安排</button>}<button className="btn primary" disabled={busy||selected.length!==4} onClick={async()=>{if(arranging&&await act(arranging.next?'plan':'assign',{court:arranging.court.id,members:selected,expectedStartedAt:arranging.court.startedAt,expectedPlayers:arranging.court.players,expectedNextPlayers:arranging.court.nextPlayers||[]}))setArranging(null);}}>{busy?'正在保存…':arranging?.next?'确认下一场安排':arranging?.court.players.length?'确认调整人员':'确认四人开场'}</button></div></DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>{if(confirm)act(confirm.action,confirm.body);}}>确认操作</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v)setEditing(null);}}><DialogContent><DialogHeader><DialogTitle>修改学生姓名</DialogTitle><DialogDescription>姓名将显示在场地和队列中。</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();act('rename',{member:editing?.id,name:editName});setEditing(null);}}><label className="field">显示姓名<input required maxLength={40} value={editName} onChange={e=>setEditName(e.target.value)}/></label><button className="btn primary full" type="submit">保存姓名</button></form></DialogContent></Dialog></>;
}
